### ISSUE TITLE
Hey it's getting an error 

### ISSUE THREAD

**Issue by GurjotSingh1105** [Zalander0/Aliucord-Plugins#1]
It's getting an error I will attach ss, so you can see 
![IMG_20220415_165350](https://user-images.githubusercontent.com/91042395/163565304-d89dbc4b-0031-44a3-b08b-f2a36eae04b2.jpg)

**Comment by GurjotSingh1105** [comment]
Can you fix it?🙄

**Comment by Zalander0** [comment]
ok i fixed it apparantly i pushed the wrong button and it didnt push 💀

**Comment by GurjotSingh1105** [comment]
Hey still getting the same error 😅

**Comment by anonymousomeone** [comment]
:2doom: did you delete the old file

**Comment by GurjotSingh1105** [comment]
Lmao 😆 sorry i forgot to install the new
